library/book/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  3 22:00:39 2023

@author: Sonya
"""

from django.urls import path
from . import views
app_name = 'book'


urlpatterns = [
    path("", views.books_page, name='book_main_page'),
    path("<int:book_id>/", views.book_detail, name='book_detail'),
    path("book/add_author/<int:book_id>/", views.add_author, name='add_author'),
    #path("book/add_book/", views.add_book, name='add_book'),
    path("book/new_book/", views.new_book, name='new_book'),
    path("book_add_page/", views.book_add_page, name='book_add_page'),
    path("book/add_book/", views.BookCreateView.as_view(), name='add_book'),
    path("edit/<pk>/", views.BookUpdate.as_view(), name='edit'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("home/", include("authentication.urls")),
    path("author/", include("author.urls")),
    path("book/", include("book.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
]

library/book/models.py
from django.db import models
from author.models import Author
from django.urls import reverse
class Book(models.Model):
    """
        This class represents an Book. \n
        Attributes:
        -----------
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(blank=False, max_length=128)
    description = models.CharField(blank=True, max_length=256)
    count = models.IntegerField(default=10, blank=True)
    authors =  models.ManyToManyField(Author, blank=True)
    
    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        author_list=[]
        for elem in self.authors.all():
            author_list.append(' '.join([elem.name, elem.surname]))
            
        return f" id: {self.id}, book: {self.name}, authors: {', '.join(author_list)}"
    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f"Book(id={self.id})"
    @staticmethod
    def get_by_id(book_id):
        """
        :param book_id: SERIAL: the id of a Book to be found in the DB
        :return: book object or None if a book with such ID does not exist
        """
        return Book.objects.get(id=book_id) if Book.objects.filter(id=book_id) else None
    @staticmethod
    def delete_by_id(book_id):
        """
        :param book_id: an id of a book to be deleted
        :type book_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        if Book.get_by_id(book_id) is None:
            return False
        Book.objects.get(id=book_id).delete()
        return True
    @staticmethod
    def create(name, description, count=10, authors=[]):
        """
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
        :return: a new book object which is also written into the DB
        """
        if len(name) > 128:
            return None

        book = Book()
        book.name = name
        book.description = description
        book.count = count
        book.save()
        if isinstance(authors, list):
            for elem in authors:
                book.authors.add(elem)
        else:
            book.authors=[].append(authors)
        book.save()
        return book
        book.save()
        return book
    def to_dict(self):
        """
        :return: book id, book name, book description, book count, book authors
        :Example:
        | {
        |   'id': 8,
        |   'name': 'django book',
        |   'description': 'bla bla bla',
        |   'count': 10',
        |   'authors': []
        | }
        """
        return {'id': self.id,
                'name': f'{self.name}',
                'description': f'{self.description}',
                'count': f'{self.count}',
                'authors': f'{self.authors}'}
    def update(self, name=None, description=None, count=None):
        """
        Updates book in the database with the specified parameters.\n
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        :return: None
        """
        if name is not None:
            self.name = name

        if description is not None:
            self.description = description

        if count is not None:
            self.count = count

        if self.count < 0:
            self.count = 0

        self.save()

    def add_authors(self, authors):
        """
        Add  authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        if (authors is not None):
            for elem in authors:
                self.authors.add(elem)
                self.save()

    def remove_authors(self, authors):
        """
        Remove authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        for elem in self.authors.values():
            self.authors.remove(elem['id'])
    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all books
        """
        return list(Book.objects.all())
    def get_absolute_url(self):
        return reverse('book:book_detail', args=[self.id])

library/book/forms.py
from django import forms

from .models import Book

class BookCreateForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('name', 'description', 'count', 'authors')

library/book/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .models import Book
from .models import Author
from authentication.models import CustomUser
from order.models import Order
from django.utils.datastructures import MultiValueDictKeyError
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from .forms import BookCreateForm
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
@login_required
def books_page(request):
    user=CustomUser.objects.all
    book=Book.objects.all()
    try:
        if request.POST['parameter']==None or not request.POST['value']: 
            book=Book.objects.all()            
        elif request.POST['parameter']=="authors":
            book=Book.objects.filter(authors=request.POST['value']).values()
        elif request.POST['parameter']=="title":
            book=Book.objects.filter(name=request.POST['value']).values()
        elif request.POST['parameter']=="count":
            book=Book.objects.filter(count=request.POST['value']).values()
        

    except (MultiValueDictKeyError):
        book=Book.objects.all()
        
    return render(request, template_name='book/basik.html',
                  context={'books': book, 'user': user})

def book_add_page(request):
    user=CustomUser.objects.all
    book=Book.objects.all()
    try:
        if request.POST['user']:
            all_order=Order.objects.all()
            book=[]
            for elem in all_order:
                if elem.user.id==int(request.POST['user']):
                    book.append(elem.book)
    except (MultiValueDictKeyError):
        book=Book.objects.all()
    return render(request, template_name='book/basik.html',
                  context={'books': book, 'user': user})


@login_required
def book_detail(request, book_id):
    orders=Order.objects.all()
    not_avaliable=0
    for elem in orders:
        if elem.end_at==None and elem.book.id==book_id:
            not_avaliable+=1
    
    authors=Author.objects.all()
    book=Book.objects.get(id=book_id)
    book_authors=book.authors.all()
    avaliable=book.count-not_avaliable
    return render(request, template_name='book/book.html',
                  context={'book': Book.get_by_id(book_id), 'authors':authors, 'book_authors':book_authors, 'avaliable':avaliable})


@login_required
def add_author(request, book_id):
    author_id = request.POST["author"]
    book = Book.objects.get(id=book_id)
    book.authors.add(Author.objects.get(id=author_id))
    book.save()
    return render(
        request,
        template_name="book/book.html",
        context={
            "book": Book.get_by_id(book_id),
            "authors": Author.objects.all(),
            "book_authors": book.authors.all(),
        },
    )

"""
def add_book(request):
    return render(
        request,
        template_name="book/add_book.html",
        context={"authors": Author.objects.all()},
    )
"""

def new_book(request):
    name = request.POST["name"]
    description = request.POST["description"]
    count = request.POST["count"]
    authors = request.POST["authors"]
    if authors == "None":
        book = Book.create(name=name, description=description, count=count)
        book.save()
    else:
        book = Book.create(name=name, description=description, count=count)
        book.save()
        book.authors.add(Author.objects.get(id=authors))
        book.save()
    return books_page(request)

class BookCreateView(CreateView):
    template_name = 'book/book-create.html'
    form_class = BookCreateForm
    
    # def get(self, request, *args, **kwargs):
    #     context = {'form': BookCreateForm()}
    #     return render(request, 'book/book-create.html', context)

    # def post(self, request, *args, **kwargs):
    #     form = BookCreateForm(request.POST)
    #     if form.is_valid():
    #         book = form.save()
    #         book.save()
    #         return HttpResponseRedirect(reverse_lazy('book:book_detail', args=[book.id]))
    #     return render(request, 'book/book-create.html', {'form': form})

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'

    def get(self, request, pk):
        context = {'form': BookCreateForm(instance=Book.objects.get(id=pk))}
        return render(request, 'book/book_update_form.html', context)

    def post(self, request, pk):
        form = BookCreateForm(request.POST, instance=Book.objects.get(id=pk))
        if form.is_valid():
            book = form.save()
            book.save()
            return HttpResponseRedirect(reverse_lazy('book:book_detail', args=[book.id]))

    

library/book/templates/book/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{book.name}}</title>
</head>
<body>
<p> <a href="/home/out"> Log out</a></p>
<p> <a href="/home"> Home </a></p>
<h1>Create new book:</h1>


{% if request.user.role == 1 %}
    <form action="{% url 'book:new_book' %}", method = "post", target= _blank>
    {% csrf_token %}
      {% csrf_token %}
        <label for="name">Name:</label><br>
          <input type="text" id="name" name="name"><br>
        <label for="description">Description:</label><br>
          <input type="text" id="description" name="description"><br>
         <label for="count">Count:</label><br>
           <input type="number" id="count" name="count"><br>
         <label for="authors">Choose an author:</label><br>
         
          <select id="authors" name="authors" size="5">
          <option value="None">None</option>
            {% for x in authors %}
            <option value="{{x.id}}">{{x.name}} {{x.surname}} {{x.patronymic}}</option>
            {% endfor %}            
          </select><br><br>
        <button type="submit">CREATE</button>
    </form>
{% endif %}

<p> Return back to the <a href="/book">book</a> list.</p>

</body>
</html>

library/book/templates/book/basik.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library</title>
</head>
<body>
<p> <a href="/home/out"> Log out</a>.</p>
<p> <a href="/home"> Home </a></p>
<h1>This is a list of avaliable books:</h1>
<form action="{% url 'book:book_main_page' %}", method = "post", target = "_self">
{% csrf_token %}
  <label for="parameter">Choose a filter parameter:</label>
  <select id="parameter" name="parameter">
    <option value="None">None</option>
    <option value="authors">authors</option>
    <option value="title">title</option>
    <option value="count">count</option>
    <label for="value"></label><br>
      <input type="text" id="value" name="value">
  </select>
  <button type="submit">Filter</button>
</form><br>
{% if request.user.role == 1 %}
    <form action="{% url 'book:book_add_page' %}", method = "post", target = "_self">
    {% csrf_token %}
      <label for="user">Choose a user:</label>
      <select id="user" name="user">
      {% for x in user %}
      <option value="{{x.id}}">{{x.email}}</option>
      {% endfor %}
      </select>
      <button type="submit">Filter</button>
    </form><br>
{% endif %}
{% if request.user.role == 1 %}
    <form action="{% url 'book:add_book' %}", target= "_self">
    {% csrf_token %}
      <button type="submit">ADD NEW BOOK</button>
    </form>
{% endif %}
<ul>
  {% for x in books %}
    <li><a href="/book/{{ x.id }}">{{ x.name}}</a></li>
  {% endfor %}
</ul>

</body>
</html>

library/book/templates/book/book-create.html
<!--books/templates/books/book-create.html-->

<form action="." method="POST">

{% csrf_token %}
{{ form.as_p }}
<table>

</table>
<button type="submit">SUBMIT</button>
</form>

<p> Return back to the <a href="/book">book</a> list.</p>

library/book/templates/book/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{book.name}}</title>
</head>
<body>
<p> <a href="/home/out"> Log out</a></p>
<p> <a href="/home"> Home </a></p>
<h1>Information about book:</h1>
{% if request.user.role == 1 %}
<p><a href="/book/edit/{{ book.id }}">EDIT</a></p>
{% endif %}
<p>Name: {{book.name}}</p>
<p>Author: {% for elem in book_authors %}
            {{elem.name}} {{elem.surname}} {{elem.patronymic}},
            {% endfor %} 

</p>
<p>Count: {{book.count}}</p>
<p>Avaliable count: {{avaliable}}</p>
<p>Descriptions: </br>
{{book.description}}</p>
</br>

<p> Return back to the <a href="/book">book</a> list.</p>

</body>
</html>

library/book/templates/book/book_update_form.html
<form action="." method="POST">

{% csrf_token %}
{{ form.as_p }}
<table>

</table>
<button type="submit">SUBMIT</button>

<p> Return back to the <a href="/book">book</a> list.</p>
</form>

library/book/templates/book/user_books.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Books</title>
  </head>
  <body>
    <p><a href="/home/out"> Log out</a></p>
    <p><a href="/home"> Home </a></p>
    {% if user != None %}
      <h1>Information about User id = {{user_id}} books:</h1>

      {% if books %}

        {% for book in books %}
        <p> - Title: {{book.name}} Description: {{book.description}}</p>
        {% endfor %}
      {%  else %}
      <p> User doesn't have any books</p>
      {% endif %}
    {% else %}
    <h1>No User</h1>
    {% endif %}

  </body>
</html>

library/book/templates/book/users.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Choose User</title>
  </head>
  <body>
    <p><a href="/home/out"> Log out</a></p>
    <p><a href="/home"> Home </a></p>
    <h1>Information about user's books:</h1>
    <h2>Find user</h2>
    <ul>
      {% for user in users %}
      <li>
        User id: - {{ user.id }} -
        <a href="{% url 'book:user_books' user.id %}"> List of books </a>
      </li>
      {% empty %}
      <li>No user yet.</li>
      {% endfor %}
    </ul>
  </body>
</html>