library/book/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  3 22:00:39 2023

@author: Sonya
"""

from django.urls import path
from . import views
app_name = 'book'


urlpatterns = [
    path("", views.books_page, name='book_main_page'),
    path("<int:book_id>/", views.book_detail, name='book_detail'),
    path("book/add_author/<int:book_id>/", views.add_author, name='add_author'),
    #path("book/add_book/", views.add_book, name='add_book'),
    path("book/new_book/", views.new_book, name='new_book'),
    path("book_add_page/", views.book_add_page, name='book_add_page'),
    path("book/add_book/", views.BookCreateView.as_view(), name='add_book'),
    path("edit/<pk>/", views.BookUpdate.as_view(), name='edit'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("home/", include("authentication.urls")),
    path("author/", include("author.urls")),
    path("book/", include("book.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
]

library/order/urls.py
from django.urls import path
from . import views
from utils import deny_non_librarian

app_name = "order"

urlpatterns = [
    path("", deny_non_librarian(views.order_list), name="order"),
    path("create/", (views.create_order), name="create_order"),
    path("user/", (views.user_orders), name="user_orders"),
    path("close/<int:order_id>/", (views.close_order), name="close_order"),
]

library/order/models.py
from django.db import models, DataError

from authentication.models import CustomUser
from book.models import Book


class Order(models.Model):
    """
    This class represents an Order. \n
    Attributes:
    -----------
    param book: foreign key Book
    type book: ForeignKey
    param user: foreign key CustomUser
    type user: ForeignKey
    param created_at: Describes the date when the order was created. Can't be changed.
    type created_at: int (timestamp)
    param end_at: Describes the actual return date of the book. (`None` if not returned)
    type end_at: int (timestamp)
    param plated_end_at: Describes the planned return period of the book (2 weeks from the moment of creation).
    type plated_end_at: int (timestamp)
    """

    book = models.ForeignKey(Book, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    end_at = models.DateTimeField(default=None, null=True, blank=True)
    plated_end_at = models.DateTimeField(default=None)

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        if self.end_at == None:
            return (
                f"'id': {self.pk}, "
                f"'user': CustomUser(id={self.user.pk}),"
                f" 'book': Book(id={self.book.pk}),"
                f" 'created_at': '{self.created_at}',"
                f" 'end_at': {self.end_at},"
                f" 'plated_end_at': '{self.plated_end_at}'"
            )
        else:
            return (
                f"'id': {self.pk}, "
                f"'user': CustomUser(id={self.user.pk}),"
                f" 'book': Book(id={self.book.pk}),"
                f" 'created_at': '{self.created_at}',"
                f" 'end_at': '{self.end_at}',"
                f" 'plated_end_at': '{self.plated_end_at}'"
            )

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f"{self.__class__.__name__}(id={self.id})"

    def to_dict(self):
        """
        :return: order id, book id, user id, order created_at, order end_at, order plated_end_at
        :Example:
        | {
        |   'id': 8,
        |   'book': 8,
        |   'user': 8',
        |   'created_at': 1509393504,
        |   'end_at': 1509393504,
        |   'plated_end_at': 1509402866,
        | }
        """
        pass

    @staticmethod
    def create(user, book, plated_end_at):
        orders = Order.objects.all()
        books = set()
        for order in orders:
            if not order.end_at:
                books.add(order.book.id)
        if book.id in books and book.count == 1:
            return None
        try:
            order = Order(user=user, book=book, plated_end_at=plated_end_at)
            order.save()
            return order
        except ValueError:
            return None
        except DataError:
            return None

    @staticmethod
    def get_by_id(order_id):
        try:
            return Order.objects.get(pk=order_id)
        except:
            return None

    def update(self, plated_end_at=None, end_at=None):
        if plated_end_at != None:
            self.plated_end_at = plated_end_at
        if end_at != None:
            self.end_at = end_at
        self.save()

    @staticmethod
    def get_all():
        return list(Order.objects.all())

    @staticmethod
    def get_not_returned_books():
        return Order.objects.filter(end_at=None).values()

    @staticmethod
    def delete_by_id(order_id):
        try:
            a = Order.objects.get(pk=order_id)
        except:
            return False
        else:
            a.delete()
            return True

library/order/forms.py
from django import forms
from .models import Order


class CreateOrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ('book', 'plated_end_at')
        widgets = {
            "plated_end_at": forms.DateInput(attrs={'type': 'date'}),
        }
        
        

library/order/views.py
from .models import Order
from django.shortcuts import render, redirect
from book.models import Book
from datetime import datetime
from django.contrib import messages
from .forms import CreateOrderForm


def order_list(request):
    orders = Order.objects.order_by("user__id")
    return render(request, "order/order.html", {"orders": orders})


def user_orders(request):
    current_user = request.user
    orders = Order.objects.filter(user=current_user)
    return render(request, "order/user_orders.html", {"orders": orders})


def create_order(request):
    current_user = request.user
    books = Book.objects.all()

    if request.method == "POST":
        form = CreateOrderForm(request.POST)
        if form.is_valid():

            book = request.POST["book"]
            plated_end_at = request.POST["plated_end_at"]

            try:
                book = Book.objects.get(id=book)
            except Book.DoesNotExist:
                messages.error(request, "Invalid user or book.")
                return redirect("create_order")

            if book.count == 0:
                messages.error(request, "No book, you can`t order this book")

            else:
                order = Order.create(user=current_user, book=book, plated_end_at=plated_end_at)
                book.count -= 1
                book.update()
                messages.success(request, "Order created successfully.")
    else:
        form = CreateOrderForm()
    return render(
        request,
        "order/create_order.html",{'form':form}
    )


def close_order(request, order_id):
    order = Order.get_by_id(order_id)

    if order:
        order.update(end_at=datetime.now())

    return redirect("order:order")

library/order/templates/order/close_order.html
{% extends 'base_order.html' %}


{% block content %}

<form method="POST" action="{% url 'close_order' order_id=order.id %}">
    {% csrf_token %}
    <button type="submit">Close Order</button>
  </form>

{% endblock %}

library/order/templates/order/create_order.html
{% extends 'base_order.html' %}


{% block content %}


    <h2>Create Order</h2>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    <form method="post" action="{% url 'order:create_order' %}">
        {% csrf_token %}
        {{form.as_p}}
        <!-- <label for="book_id">Book:</label>
        <select id="book_id" name="book_id" required>
          <option value="">Select a book</option>
          {% for book in books %}
            <option value="{{ book.id }}">{{ book.name }}</option>
          {% endfor %}
        </select>
        <br>
        <label for="plated_end_at">Planned Return Date:</label>
        <input type="date" id="plated_end_at" name="plated_end_at" required>
        <br> -->
        <button type="submit">Create Order</button>
      </form>

      <form method="post" action="{% url 'order:create_order' %}">
        {% csrf_token %}

      </form>

{% endblock %}

library/order/templates/order/order.html
{% extends 'base_order.html' %}


{% block content %}
<H1>THIS IS Order APP PAGE! CONGRATULATIONS!</H1>
<h2>All Orders:</h2>
<ul>

{% for order in orders %}
    <li>
        <p>User: {{ order.user.first_name }} - {{ order.user.last_name }} - {{ order.user.middle_name }} - id:{{ order.user.id }} </p> 
        <p>Book: {{ order.book.name }} </p>
            <p>Order created at : {{ order.created_at }} </p> 
                <p>Order plated end at: {{ order.plated_end_at }}</p> 
        {% if not order.end_at %}
        <form action="{% url 'order:close_order' order.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Close Order</button>
        </form>
        {% else %}
        <p>--- Order end at: -{{ order.end_at }} ---</p>
        {% endif %}
        <br>
{% empty %}
    <li>No orders yet.</li>
{% endfor %}

{% endblock %}

library/order/templates/order/user_orders.html
{% extends 'base_order.html' %}


{% block content %}
    <H1>THIS IS Order APP PAGE! CONGRATULATIONS!</H1>
    <h2>My Orders:</h2>
    <ul>

    {% for order in orders %}
        <li>
            <p>Book: {{ order.book.name }} </p>
                <p>Order created at : {{ order.created_at }} </p> 
                    <p>Order plated end at: {{ order.plated_end_at }}</p> 
                    <p>Order end at: -{{ order.end_at }}-</p> 
    {% empty %}
        <li>No orders yet.</li>
    {% endfor %}

{% endblock %}