library/authentication/urls.py
from django.urls import path
from . import views
from utils import deny_non_librarian


app_name = "authentication"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="index"),
    path("register/", views.registration, name="registration"),
    path("login/", views.LoginPage.as_view(), name="login"),
    path("authentication/", views.user_page, name="user_page"),
    path("out/", views.out, name="log_out"),
    path("users/", deny_non_librarian(views.users_page), name="all_users"),
    path(
        "user/<int:user_id>",
        deny_non_librarian(views.user_details),
        name="special_user",
    ),
]

library/author/urls.py
from django.urls import path
from . import views
from library.functions import deny_non_librarian


app_name = 'author'

urlpatterns = [
    path("", deny_non_librarian(views.AuthorPage.as_view()), name='author'),
    path("<int:pk>", deny_non_librarian(views.AuthorDetails.as_view()), name='details'),
    path("<int:author_id>/remove", deny_non_librarian(views.remove_author), name='remove_author'),
    path("new/", deny_non_librarian(views. AuthorCreateView.as_view()), name='add_author'),
    #path("submit/", deny_non_librarian(views.submit_add_author), name='submit_new_author'),
    path("edit/<pk>", deny_non_librarian(views.AuthorUpdate.as_view()), name='edit')
]

library/book/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  3 22:00:39 2023

@author: Sonya
"""

from django.urls import path
from . import views
app_name = 'book'


urlpatterns = [
    path("", views.books_page, name='book_main_page'),
    path("<int:book_id>/", views.book_detail, name='book_detail'),
    path("book/add_author/<int:book_id>/", views.add_author, name='add_author'),
    #path("book/add_book/", views.add_book, name='add_book'),
    path("book/new_book/", views.new_book, name='new_book'),
    path("book_add_page/", views.book_add_page, name='book_add_page'),
    path("book/add_book/", views.BookCreateView.as_view(), name='add_book'),
    path("edit/<pk>/", views.BookUpdate.as_view(), name='edit'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("home/", include("authentication.urls")),
    path("author/", include("author.urls")),
    path("book/", include("book.urls")),
    path("order/", include("order.urls")),
    path("admin/", admin.site.urls),
]

library/order/urls.py
from django.urls import path
from . import views
from utils import deny_non_librarian

app_name = "order"

urlpatterns = [
    path("", deny_non_librarian(views.order_list), name="order"),
    path("create/", (views.create_order), name="create_order"),
    path("user/", (views.user_orders), name="user_orders"),
    path("close/<int:order_id>/", (views.close_order), name="close_order"),
]

library/authentication/forms.py
from django import forms
from .models import *


class RegistrationForm(forms.ModelForm):
    role = forms.ChoiceField(choices=ROLE_CHOICES)
    def __init__(self, *args, **kwargs):
        super(RegistrationForm,self).__init__(*args,**kwargs)

    class Meta:
        model = CustomUser
        fields = [ 'email', 'password','role']
        widgets = {
        'password': forms.PasswordInput(),
    }
        labels = { 'role': 'Choose a role' }

    def save(self, commit=True):
        instance = super().save(commit=False)
        role = self.cleaned_data.get('role')
        instance.set_password(self.cleaned_data.get('password'))
        if role == '1':
            instance.is_staff = True
            instance.is_superuser = True

        if commit:
            instance.save()
        return instance

class LoginForm(forms.Form):
    email = forms.EmailField(required=True, error_messages={'required': 'Email is required.'})
    password = forms.CharField(widget=forms.PasswordInput())
    fields=['email', 'password']

library/authentication/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.base import TemplateView
from django.template import loader
from .models import CustomUser
from django.contrib.auth import authenticate, login, logout
from django.db.utils import IntegrityError
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from order.models import Order
from .forms import RegistrationForm, LoginForm
from django.contrib.auth.password_validation import validate_password


class HomePageView(TemplateView):
    template_name = "authentication/index.html"


class RegisterPage(TemplateView):
    template_name = "authentication/register.html"


class LoginPage(TemplateView):
    # template_name = "authentication/login.html"
    # form_class = LoginForm
    def get(self, request):
        context = {'form': LoginForm()}
        return render(request, "authentication/login.html", context)
    

def user_page(request):

    if request.user and request.user.is_authenticated:
        return redirect('authentication:index')
    
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST.get("email")
            password = request.POST.get("password")
            user = authenticate(request, username=email, password=password)
            if user:
                login(request, user)
                return render(request, template_name="authentication/index.html")
            else:
                form.add_error(None, 'Incorrect Login or Password')
    else:
        form = LoginForm()

    return render(request, 'authentication/login.html', {'form':form})
# def user_page(request):
#     if request.user.is_authenticated:
#         # template = loader.get_template("authentication/user_page.html")
#         # return HttpResponse(template.render())
#         return render(request, template_name="authentication/index.html")
#     else:
#         email = request.POST["email"]
#         password = request.POST["pass"]
#         user = authenticate(request, email=email, password=password)
#         if user is not None:
#             login(request, user)
#             # template = loader.get_template("authentication/user_page.html")
#             # return HttpResponse(template.render())
#             return render(request, template_name="authentication/index.html")

#         else:
#             return HttpResponse("Error")

def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("authentication:login")
    else:
        form = RegistrationForm()

    return render(request, "authentication/register.html", {'form':form})
# def registration(request):
#     if request.method == "POST":
#         email = request.POST["email"]
#         password = request.POST["pass"]
#         role = request.POST["role"]

#         # Checking email and password for validation
#         try:
#             validate_email(email)
#         except ValidationError as error_message:
#             return render(
#                 request,
#                 template_name="authentication/register.html",
#                 context={"error_message": error_message},)

#         # Checking password for validation
#         try:
#             validate_password(password)
#         except ValidationError as error_message:
#             return render(
#                 request,
#                 template_name="authentication/register.html",
#                 context={"error_message": error_message},)

#         # if email and password valid then trying to create the new User
#         try:
#             if role == "0":
#                 user = CustomUser.objects.create_user(email=email, password=password, role=role)
#                 user.save()
#             elif role == "1":
#                 user = CustomUser.objects.create_superuser(
#                     email=email, password=password, role=role
#                 )
#                 user.save()
#         # if email not unique then return 'error_message': 'USER IS ALREADY EXIST'
#         except IntegrityError:
#             return render(
#                 request,
#                 template_name="authentication/register.html",
#                 context={
#                     "error_message": "User with that email is already exist, please Log In"
#                 },
#             )

#         # if everything is good then redirect to login page
#         return redirect("authentication:login")

#     # if request.method != 'POST', just render template
#     else:
#         return render(request, template_name="authentication/register.html")



def out(request):
    logout(request)
    return redirect('authentication:login')


def users_page(request):
    users = CustomUser.objects.order_by("id")
    return render(request, "authentication/all_users.html", {"users": users})


def user_details(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    orders = Order.objects.filter(user_id=user_id)
    return render(request, "authentication/user_details.html", {"user": user, "orders": orders})

library/authentication/templates/authentication/all_users.html
{% extends 'base.html' %}

{% block content %}
    <h2>All Users:</h2>

<table>
    <tr>
        <th>Id</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Details</th>
    </tr>

    {% for user in users %}
    <tr>       
        <th>{{ user.id }}</th>
        <td>{{user.last_name}}</td>
        <td>{{user.first_name}}</td>
        <td>{{user.middle_name}}</td>
        <td>{{user.email}}</td>
        <td>{{user.get_role_name}}</td>
        <td><a href="{% url 'authentication:special_user' user.id %}">Details</a></td>
    </tr>
    {% endfor %}
</table>
<form>
    <button formaction="{% url 'index' %}">Back</button>
</form>
{% endblock %}

library/authentication/templates/authentication/index.html
{% extends 'base.html' %}

{% block content %}
<br>
    {% if request.user.is_authenticated %}

        {% if request.user.first_name != None %}
            Hello, {{request.user.first_name}}
        {% else %}
            Hello, User
        {% endif %}
    
        {% endif %}

{% endblock %}

library/authentication/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in page</title>

</head>
<body>
<h1>Login to your account </h1>

    <form action="{% url 'authentication:user_page' %}" method="post">
    {% csrf_token %}
     {{form.as_p}}
    <button type="submit" class="btn btn-success">Log In</button>
    </form>

<p> If you haven't an account, please register new one: <a href="/home/register"> Register </a></p>
<p> Return to <a href="{% url 'index' %}"> Home page</a>.</p>
</body>
</html>

library/authentication/templates/authentication/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in page</title>

</head>
<body>
<h1>Login sucsesfully </h1>
<ul>
  {% for x in mymembers %}
    <li>{{ x.email }} {{ x.password }} {{ x.role }}</li>
  {% endfor %}
</ul>
<p> Return to <a href="/home"> Home page</a>.</p>
</body>
</html>

library/authentication/templates/authentication/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration page</title>

</head>
<body>
<h1>Create new account</h1>
<form action="{% url 'authentication:registration' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
  <button type="submit">REGISTER</button>

</form>

<p> If you already have an account: <a href="{% url 'authentication:login' %}"> Log in </a></p>
<p> Return to <a href="{% url 'index' %}"> Home page</a>.</p>

  {% if error_message %}
      <p>{{ error_message }}</p>
  {% endif %}

</body>
</html>

library/authentication/templates/authentication/user_details.html
{% extends 'base.html' %}

{% block content %}

<h2>Informathion about {{user.first_name}} {{user.last_name}}</h2>
<body>
    <p>Id: {{user.id}}</p>
    <p>Role: {% if user.role is 0 %} visitor {% else %} librarian {% endif %}</p>
    <p>Orders: {{ orders|length }} </p>
    <p>First_name: {{user.first_name}}</p>
    <p>Last_name: {{user.last_name}}</p>
    <p>Middle_name: {{user.middle_name}}</p>
    <p>Email: {{user.email}}</p>
    <p>Created_at: {{user.created_at}}</p>
    <p>Updated_at: {{user.updated_at}}</p>
</body>
{% endblock %}

library/authentication/templates/authentication/user_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <H1>Library</H1>
    <br>
    {% if user.is_authenticated %}
    <a class="button" href="/home/out">Log out</a>
    <br>
    <br>
    <a href="{% url 'book:book_main_page' %}"> Books page </a>
    <br>
    {% if request.user.is_superuser %}
    <br>
    <a href="{% url 'author:author' %}"> Authors page </a>
    <br>
    {% endif %}
    <br>
    <a href="{% url 'order:create_order' %}"> Orders page</a>
    {% endif %}
</body>
</html>